name: Executar Robo SeaTalk

on:
  workflow_dispatch: # Botão manual
  # schedule:
  #   - cron: '0 9 * * 1-5' # Opcional: roda às 09:00 de Seg a Sex

jobs:
  automacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Bibliotecas
        run: |
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Executar Script
        env:
          EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
          SENHA_LOGIN: ${{ secrets.SENHA_LOGIN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python automacao_login.py
