name: automacao

on:
  workflow_dispatch: # Permite rodar manual
  # schedule:
  #   - cron: '0 * * * *' # Exemplo: Roda de hora em hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Faz cache automático das bibliotecas do pip

      - name: Instalar Bibliotecas
        run: |
          pip install playwright requests
      - name: Cache do Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/main.py') }}

      - name: Instalar Navegador (Apenas se não houver cache)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: playwright install chromium --with-deps

      - name: Executar Script
        env:
          EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
          SENHA_LOGIN: ${{ secrets.SENHA_LOGIN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py
